apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJZWEpqYURwbmFIQmZOVWhpWW5ObVMwNDROVFEwVlV0MVFWRllSbFZoUTBwNGNUaDBUakY1TVhOaU9VdHgifX19
type: kubernetes.io/dockerconfigjson
